### ISSUE TITLE
Pre-reqs and other issues

### ISSUE THREAD

**Issue by nickrager** [Tim-Radcliffe/Tintin-Setup#1]
I understand this is still in progress so I may be jumping the gun a little.

What are the pre-reqs for this?
I was getting errors on startup and whenever I pressed a number (1,2,3) until I installed TMUX
are there any others? Do i need to be starting TMUX in any way before going out hunting?

Other observations:
While playing 3k most of the triggers are not going off. For example:
#ACTION {^{>\s|}{You've killed|(.*) dealt the killing blow to} %*.
I defeat a monster and it does not fire. I am confused by the "prompt" at the beginning of this and many other actions. While playing, your prompt (>\s) doesn't show up on every line. though it is possible for it to, if you pressed enter on a bunch of blank commands. I have set the prompt to be what is suggested in the readme. Also the syntax with the vertical bar at the end. {^{>\s|}, my understanding is it would be read as "a > followed by whitespace OR nothing" similar to how "You've killed OR (.*) dealt the killing blow to" there are multiple places that this syntax shows up.

when logging in, the character defaults to the adventurer guild, until you do a score and then re-read 
#read Mud/3k/initialise.tin making most of the guild stuff unavailable. I have also had to manually disable salve (auto salve)

I would appreciate some guidance in using the tool.

**Comment by Tim-Radcliffe** [comment]
Didn't spot this issue report was here till now, hence the slow response. Looks like I need to dig into the notification settings of github!

I have just had a look and realised TMUX is being referred to within the System/screen.tin code, so unintentionally TMUX is currently a pre-req (even though you don't actually need to use TMUX, it works fine without it). I'll have a look at how to remove that connection so it's no longer required to be installed.

The {>\s|} section of the killed trigger is saying it is looking for EITHER "> You've killed" or "You've killed" at the start of the line. If your prompt is set to anything else, or your kill message is something else, this trigger may not fire. The point of having this in here is to avoid the situation of it firing if someone sent you a tell with "You've killed" within it....it has to be at the start of the line, on it's own or preceded by the prompt.

Could you give me a cut/paste of what you get on your killed line if it is different to the above, so I can see where it is going wrong.

Your personal settings and variables (auto, guild information, current HP etc) save every 15 minutes at the moment. You could force them to save immediately by calling .aGlobalSave, which will generate/update a persistent data file for your currently character within the data folder. That way when you next log in, the guild info is retained and it won't load the adventurer defaults. I am also at ways of having those settings also save at specific key points (such as dying, quitting etc) but that is not yet in place.

**Comment by nickrager** [comment]
It looks like an update was made to Tintin that is busting your setup. When I start, it doesn't have a list of players anymore and when I try to add one, it throws the error below.

~/Documents/playground/Tintin-Setup (master) $ tt++ start.tin

                     Lost Souls  -  http://lostsouls.org

"Lost Souls is not for the faint of heart." -- Net Games

"The depth of Lost Souls can be amazing." -- Playing MUDs On The Internet

"Have you ever come upon a place on the Net that's so incredible that you
can't believe such entertainment is free? This MUD will blow your mind with
its marvelous attention to detail and incredible role-playing atmosphere!"
  -- Yahoo! Wild Web Rides

To connect to Lost Souls enter: #session ls lostsouls.org 23

      ####################################################################
      #                     T I N T I N + +   2.01.6                     #
      #                                                                  #
      #                 The Kickin Tickin DikuMUD Client                 #
      #                                                                  #
      #      Code by Peter Unold, Bill Reis, and Igor van den Hoven      #
      ####################################################################


Choose a player
===============


Or press '+' to add a new profile or press '0' to exit
#NOTICE: The #forall command no longer exists, please switch to the #foreach command.

Enter Game/Mud system name (e.g. 3K):
\e\cd
#NO SESSION ACTIVE. USE: #session {name} {host} {port} TO START ONE.

Goodbye from TinTin++

**Comment by Tim-Radcliffe** [comment]
Currently working on updating to use the latest version of Tintin++ (2.02.02 at time of writing). 

All #FORALL entries should now be removed and replaced with #FOREACH as of most recent commit. #2dc59c4
